# Generated by Django 6.0 on 2025-12-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='role',
            field=models.CharField(default='volunteer', max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
        ),
    ]
