# Generated by Django 6.0 on 2025-12-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_is_active_volunteer_role_volunteertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
